# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conv_NA_float <- function(source) {
    .Call(`_rmio_conv_NA_float`, source)
}

extractVec <- function(BM, elemInd) {
    .Call(`_rmio_extractVec`, BM, elemInd)
}

extractMat <- function(BM, rowInd, colInd) {
    .Call(`_rmio_extractMat`, BM, rowInd, colInd)
}

createFile <- function(fileName, nrow, ncol, type) {
    invisible(.Call(`_rmio_createFile`, fileName, nrow, ncol, type))
}

addColumns <- function(fileName, nrow, ncol_add, type) {
    invisible(.Call(`_rmio_addColumns`, fileName, nrow, ncol_add, type))
}

replaceVecOne <- function(xpbm, elemInd, val) {
    invisible(.Call(`_rmio_replaceVecOne`, xpbm, elemInd, val))
}

replaceVec <- function(xpbm, elemInd, vec) {
    invisible(.Call(`_rmio_replaceVec`, xpbm, elemInd, vec))
}

replaceMatOne <- function(xpbm, rowInd, colInd, val) {
    invisible(.Call(`_rmio_replaceMatOne`, xpbm, rowInd, colInd, val))
}

replaceMat <- function(xpbm, rowInd, colInd, mat) {
    invisible(.Call(`_rmio_replaceMat`, xpbm, rowInd, colInd, mat))
}

replaceDF <- function(xpbm, rowInd, colInd, df) {
    invisible(.Call(`_rmio_replaceDF`, xpbm, rowInd, colInd, df))
}

getXPtrFBM <- function(path, n, m, type) {
    .Call(`_rmio_getXPtrFBM`, path, n, m, type)
}

getXPtrFBM_RW <- function(path, n, m, type) {
    .Call(`_rmio_getXPtrFBM_RW`, path, n, m, type)
}

mycount1 <- function(BM, rowInd, colInd, codeInd) {
    .Call(`_rmio_mycount1`, BM, rowInd, colInd, codeInd)
}

mycount2 <- function(BM, rowInd, colInd, codeInd) {
    .Call(`_rmio_mycount2`, BM, rowInd, colInd, codeInd)
}

incr_FBM_mat <- function(BM, mat) {
    invisible(.Call(`_rmio_incr_FBM_mat`, BM, mat))
}

incr_FBM_vec <- function(BM, vec) {
    invisible(.Call(`_rmio_incr_FBM_vec`, BM, vec))
}

transpose3 <- function(BM, BM2) {
    invisible(.Call(`_rmio_transpose3`, BM, BM2))
}

